name: Publish artifact

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -f source/pom.xml package
    - name: Publish Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: taskmanager
        username: ${{ secrets.nexus_username }}
        password: ${{ secrets.nexus_password }}
        registry: nexus-docker.aerius.nl
        workdir: source/
    - name: Publish Maven Artifacts
      uses: samuelmeuli/action-maven-publish@v1
      with:
        server_id: aerius-nexus
        nexus_username: ${{ secrets.nexus_username }}
        nexus_password: ${{ secrets.nexus_password }}
        directory: source/
        # Tests are already run in the Build step, no use running them again
        maven_args: -DskipTests
